version: '3.4'

services:
  localstack:
    container_name: harpoon_localstack
#    image: localstack/localstack
#    can't use latest image until https://github.com/localstack/localstack/issues/308 is fixed :(
    image: atlassianlabs/localstack
    environment:
      - TERM=xterm
      - SERVICES=${LOCALSTACK_SERVICES}
      - DEFAULT_REGION
      - HOSTNAME=${HARPOON_DOCKER_HOST_IP}
      - KINESIS_ERROR_PROBABILITY
      - DYNAMODB_ERROR_PROBABILITY
      - LAMBDA_EXECUTOR
      - DATA_DIR
      - DOCKER_HOST="unix:///var/run/docker.sock"
    labels:
      - "traefik.backend=localstack"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${LS_HOSTS}"
      - "traefik.frontend.entryPoints=${FRONTEND_ENTRYPOINTS}"
      - "traefik.docker.network=${HARPOON_DOCKER_NETWORK}"
      - "traefik.tags=${TRAEFIK_DOCKER_TAGS}"
      - "SERVICE_8080_NAME=localstack"
    ports:
      - "8080"
      - ${PORT_MAPPINGS}
    networks:
      default:
        aliases:
          - localstack.${HARPOON_INT_DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TMP_DIR}:${TMP_DIR}

networks:
  default:
    external:
      name: ${HARPOON_DOCKER_NETWORK}